### ISSUE TITLE
.value with roundtrip does not update sub-dicts

### ISSUE THREAD

**Issue by J0hnL0cke** [gpoore/bespon_py#1]
When the value in a nested dictionary is changed, calling `.dumps()` or calling `.value` or on a parent dictionary sometimes does not show the updated values of the child.

To reproduce:
```
import bespon
ast=bespon.loads_roundtrip_ast("""
a=
    b=c
""")
ast['a']['b'].value='d'
print(ast.value['a']['b']) #Outputs "c" instead of "d"
print(ast['a'].value['b']) #Outputs "c" instead of "d"
print(ast['a']['b'].value) #Works as intended, prints "d"
ast.dumps() #Works as intended, prints "'\na=\n    b=d\n'"
```
`ast.replace_val(['a','b'],'d')` works the same way.

However, when the .value in the set command is moved to either of the parents, the effect is reversed:
```
import bespon
ast=bespon.loads_roundtrip_ast("""
a=
    b=c
""")
ast.value['a']['b']='d' #Changed this line (also acts the same as ast['a'].value['b']='d')
print(ast.value['a']['b']) #Works as intended, prints "d"
print(ast['a'].value['b']) #Works as intended, prints "d"
print(ast['a']['b'].value) #Outputs "c" instead of "d"
ast.dumps() #Outputs "'\na=\n    b=c\n'" instead of "'\na=\n    b=d\n'"
```
Note: Haven't tested `replace_key`

**Comment by gpoore** [comment]
There are a few different things going on here.
* There was a bug, which should be fixed by the last commit. The AST keeps an internal representation of itself (which is what `.value` returns), and this wasn't being updated for collections like lists and dicts.
* There are some limitations in the current architecture. You want to always do things like `ast['a']['b'].value='d'` instead of `ast.value['a']['b']='d'`. With `ast['a']['b'].value='d'`, you are modifying a value in the AST itself. With `ast.value['a']['b']='d'`, you are first accessing the AST's representation of itself (`ast.value`), then going into that representation (`ast.value['a']['b']`) and making an assignment. So you are changing the representation but not the AST itself. Currently, everything operates under the assumption that the representation (`ast.value`) is treated as immutable by the user; all modifications to it are made indirectly through the AST. I've updated the README to reflect this. I believe it would be possible to avoid this limitation, but likely at the expense of needing a much more complex algorithm.
